# Generated by Django 2.1.4 on 2018-12-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainnews',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
