# Generated by Django 2.1.4 on 2018-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181207_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('times', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sentibywsj_bitcoin', models.CharField(blank=True, max_length=255, null=True)),
                ('sentibywsj_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('sentibycnn_bitcoin', models.CharField(blank=True, max_length=255, null=True)),
                ('sentibycnn_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('sentibyreuters_bitcoin', models.CharField(blank=True, db_column='sentibyReuters_bitcoin', max_length=255, null=True)),
                ('sentibyreuters_blockchain', models.CharField(blank=True, db_column='sentibyReuters_blockchain', max_length=255, null=True)),
                ('sentibyft_bitcoin', models.CharField(blank=True, db_column='sentibyFT_bitcoin', max_length=255, null=True)),
                ('sentibyft_blockchain', models.CharField(blank=True, db_column='sentibyFT_blockchain', max_length=255, null=True)),
                ('daily_senti_average', models.CharField(blank=True, max_length=255, null=True)),
                ('opens', models.CharField(blank=True, max_length=255, null=True)),
                ('highs', models.CharField(blank=True, max_length=255, null=True)),
                ('lows', models.CharField(blank=True, max_length=255, null=True)),
                ('closes', models.CharField(blank=True, max_length=255, null=True)),
                ('volumes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SENTIMENT',
            },
        ),
    ]
