# Generated by Django 2.1.4 on 2018-12-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='closes',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='highs',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='lows',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='opens',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='volumes',
            new_name='volume',
        ),
    ]
